### ISSUE TITLE
Add Footer Menu for Privacy Statement, DMCA, Copyright

### ISSUE THREAD

**Issue by acketon** [bu-ist/responsive-framework#272] opened 2021-07-26 19:45 UTC
### Expected behavior:
Per the new Website Policy all sites must have new links to certain pages in the footer such as the DMCA, Copyright, Privacy Statement?, etc. 

We should consider adding a new menu and menu location to Responsive Framework that sits farther down below the footer as the current Footer Links and Social links is insufficient in many cases to separate these utility type policy required links from website content links. 

### Steps to reproduce:

1.
2.

### Screenshot (if this is a bug):
Example design: 
<img width="1590" alt="Screen Shot 2021-07-26 at 3 41 08 PM" src="https://user-images.githubusercontent.com/3139096/127049211-ff9def36-1c66-464e-a4a3-bc8fb9226d68.png">

### Related ServiceNow Ticket number (if available):

**Comment by ashleykolodziej** [comment] 2021-07-30 18:15
This is a duplicate of https://github.com/bu-ist/bu-branding/issues/6

Next steps: decide where this code belongs. This should apply both to 2x sites and 3x sites.

**Comment by ashleykolodziej** [comment] 2021-08-31 20:04
Closing as duplicate.

**Closed by ashleykolodziej** 2021-08-31 20:04 UTC
Labels: 🚫 Duplicate, 🎉 Enhancement
