### ISSUE TITLE
Inconsistencies in sidebar position behaviors

### ISSUE THREAD

**Issue by amckenz** [bu-ist/responsive-framework#71] opened 2018-09-14 14:19 UTC
_From @desrosj on March 21, 2018 19:33_

### 1.x (possibly in 2x branch as well)

As detailed in INC12390770, some users are experiencing their sidebar pushed to the bottom of the page on post and profile pages.

There are several parts to this, and I will attempt to summarize all of my research here.

## Background

In #248, a default option was added for the `burf_setting_sidebar_location` option. The default was not being saved to the database until the user opened the customizer and saved. This caused issues that were detailed in #268. A combination of `burf_setting_posts_sidebar_bottom` and `burf_setting_sidebar_location` both lacking proper default values in all scenarios was causing unintended behaviors. #268 added default values for `burf_setting_posts_sidebar_bottom`.

And that is where we are at today.

## Cause of INC12390770

This is being caused by a default value of `true` being returned for the option. While this is the correct behavior (the sidebar should show on the bottom for posts and profiles on a default Responsi site), it was causing issues for the same reason as the original #248. The option does not exist in the database until it is changed and saved in the customizer. A step further, it is not added to the database until a non `false` value is saved. After that, unchecking the option leaves the option key but empties the value.

## Ideal Behaviors

1. You create a new site: the sidebar is on the bottom
1. You migrate a site from 1x -> 2x: the sidebar setting stays at whatever you had before
1. You activate Framework on a flexi site: the sidebar is on the bottom
1. You have an existing setting already out there: it stays the same

## Different Scenarios in the Wild

1. A site that has never used the Customizer.
1. A site that has used the Customizer, but may not have edited the `burf_setting_posts_sidebar_bottom` setting.
1. A site that has used the Customizer, edited the `burf_setting_posts_sidebar_bottom` setting and saved, but the value was `false`, so the option key does not exist in the database.
1. A site that has used the Customizer, edited the `burf_setting_posts_sidebar_bottom` setting and saved, and the value was `true` at some point. The option key will exist in the database.

Because of scenarios 2 & 3, it can't be assumed that a site without the option key in the database should be added and set to `true`.

I decided to do some testing to see what the behavior is based on the different scenarios above and discovered that the behavior is not consistent across 1.5.x point releases.

## Responsi 1.5.3

https://cloudup.com/cK_yO7snurj

### Steps & Results

- No option key exists, the page shows as narrow.
- Open the customizer and it **previews differently**, showing the sidebar on the right.
- Check post sidebar on the bottom and the page previews as narrow.
- Uncheck, sidebar correctly shows on right.
- Save. The option does not get added. Front-end shows as narrow.
- Open customizer, check keep on the bottom, shows as narrow.
- Save, site shows on bottom and option saved.
- Open customizer, uncheck the option and it previews **incorrectly** as narrow.
- Save, option remains, but empty. Site shows as narrow.

## Responsi 1.5.4

https://cloudup.com/cN1VaikLu_a

### Steps & Results

- No option key exists, the page shows the sidebar on right.
- Open customizer, the option is unchecked and previews correctly with the sidebar on the right.
- Check the option and the page correctly previews as narrow.
- Uncheck the option and it correctly previews as right sidebar.
- Save. No option is saved. The page shows correctly with right sidebar.
- Open customizer, check option. Previews as narrow.
- Save. The page shows as narrow and the option is saved to the database.
- Open the customizer and uncheck the option. The page previews as **narrow** (which is incorrect).
- Save. The option is not deleted but set to empty.
- Page shows as right sidebar.

## Responsi 1.5.5

https://cloudup.com/cgbYTZpecox

### Steps & Results

- No option key exists, the page shows the sidebar on right.
- Open customizer, the option is unchecked and previews correctly with the sidebar on the right.
- Check the option and the page correctly previews as narrow.
- Uncheck the option and it correctly previews as right sidebar.
- Save. No option is saved. The page shows correctly with right sidebar.
- Open the Customizer and check option. The page previews correctly as narrow.
- Save. The page correctly shows as narrow and the option is saved to the database.
- Open the customizer and uncheck the option. The page incorrectly previews as **narrow**.
- Save. The option is not deleted but set to empty.
- The page shows correctly with the right sidebar.
- Reopen the Customizer. The option is correctly unchecked and previews correctly.

## Responsi 1.5.6

https://cloudup.com/cO2K8FiR6kE

### Steps & Results

- No option key exists, the page incorrectly shows as narrow.
- Open customizer, the option is incorrectly checked and previews incorrectly with the sidebar at the bottom.
- Uncheck the option and the page incorrectly previews as narrow.
- Check the option and the page correctly previews as narrow.
- Uncheck the option and the page incorrectly previews as narrow.
- Save. No option is saved. The page shows incorrectly as narrow.
- Open the Customizer. The option is incorrectly checked and the page previews as narrow.
- Uncheck the option. The page incorrectly previews as narrow.
- Recheck the option. It correctly previews as narrow. Save.
- The option is saved and the page correctly displays as narrow.
- Open the customizer. Uncheck the option. The page incorrectly previews as narrow.
- Save. The option remains but is empty. The page correctly displays as right sidebar.
- Open the Customizer. The option is correctly unchecked and the page correctly previews as right sidebar.
- Toggling the checkbox now always correctly previews.

### On activation

Part of the problem stems from the fact that the options are not initialized in the database when the theme is activated. On activation, the default options and values (sidebar: right, sidebar on the bottom for posts) should be added if the option keys do not already exist.

### Correct Current Sites

Correcting current sites is more difficult because of the differences in behaviors listed above. A site may be displayed exactly how the client wants it to but with the incorrect configuration.

The best way to tackle this is to fix the behaviors to work correctly when the option exists in the database and is `true` or `false`.

Since version `1.5.3` of Responsive Framework was the production version until `1.5.6` was deployed in CHG039340 on 3/7/18, and was the active version for over 6 months, the behaviors in that version should be used to determine how to _fix_ the issues to work correctly with the new, corrected version.

_Copied from original issue: bu-ist/responsive-framework-1x#364_

**Comment by toddmilliken** [comment] 2019-03-27 15:57
Its hard to tell if this is still an issue or if it was resolved in the latest PR that fixed a bug in the customizer when unchecking the option in Content Options > "Keep posts sidebar to the bottom". https://github.com/bu-ist/responsive-framework/pull/109

@ashleykolodziej or anyone else want to confirm? The value for `burf_setting_posts_sidebar_bottom` seems to be working as expected but I'm not sure what the intended behaviors are for the other customizer options on a fresh site install or upgrade.

**Comment by toddmilliken** [comment] 2019-04-03 15:28
Closing this as this resolved the ServiceNow ticket and confirmed the `burf_setting_posts_sidebar_bottom` value is being set correctly on initial theme activation and customizer save.

**Closed by toddmilliken** 2019-04-03 15:28 UTC
Labels: Needs Feedback, Testing in progress, 🔥 bug
